### ISSUE TITLE
What happens if the callbacks are changed?

### ISSUE THREAD

**Issue by barbu110** [barbu110/microloop#11]
The API of `microloop::net::TcpServer` allows changing the `on_data` and `on_conn` callbacks after they have been assigned.

https://github.com/barbu110/microloop/blob/5b5ae6d85a613e91ce22fd4193af53456aad1977/example/usage.cpp#L45-L46

Are there any potential issues of this?

**Comment by slak44** [comment]
Changing the callbacks from another thread works as expected; for new connection/data events the new callback is used. Closing.
